/*
  Scala for the Impatient Third Edition - Cay S. Horstmann
  Source code shown in the book
  Download the zip file from: https://horstmann.com/scala/

  https://github.com/egalli64/scala-playground

  5. Classes
   2. Properties with Getters and Setters
 */
package com.horstmann.scala3ed.ch05

@main
def s2_properties(): Unit =
  /**
   * A class with a property. Getter and setter are generated by Scala
   */
  class Person:
    var age = 0

  val p = Person()

  // it is actually a call to p.age_=(42), where age_= is the setter for age
  p.age = 42

  // prints the value returned from age(), the getter for age
  println(p.age)

  /**
   * A class with a property. Getter and setter are overridden
   */
  class Person2:
    private var _age = 0

    // getter
    def age: Int = _age

    // setter
    def age_=(age: Int): Unit = if age > _age then _age = age

  val p2 = Person2()

  // won't compile
//  p2._age = 12
//  println(p2._age)

  // calling the setter
  p2.age = 30

  // this setter won't set anything - see method definition above
  p2.age = 21

  // calling the getter
  println(p2.age)
